### ISSUE TITLE
Failed migrations

### ISSUE THREAD

**Issue by mfansler** [conda-forge/eth-utils-feedstock#21]
The last two Python migrations failed to generate the target build variants.

- [Python 3.10](https://github.com/conda-forge/plio-feedstock/pull/21)
- [Python 3.11](https://github.com/conda-forge/plio-feedstock/pull/24)

This is due to the `skip` condition:

https://github.com/conda-forge/eth-utils-feedstock/blob/cea1b0730c5cc99d3afb52008fba54cf4da43602/recipe/meta.yaml#L15

Is there a reason to retain this condition? Conda Forge no longer builds Python 2.x, and the intent here looks like trying to preemptively block Python 4, which seems unnecessary.

**Comment by step21** [comment]
Should be fixed in https://github.com/conda-forge/eth-utils-feedstock/pull/24
It was a leftover from the beginning, not sure anymore why exactly.
Please let me know if there are any other issues.

**Comment by mfansler** [comment]
Thanks! I can confirm the builds are now  showing up. 🙌
